### ISSUE TITLE
Add something for preprocessor variables ?

### ISSUE THREAD

**Issue by MoOx** [DSSWG/DSS#45]
It's just an idea, because for now I need to do something like that for some color

```scss
// @name Main colors
// @description Our brand colors
// @markup
//     <strong>Don't use this markup</strong>
//     <p class="color__blue">$color__blueblue</p>
//     <p class="color__orange">$color__orange</p>
//     <p class="color__green">$color__green</p>
//
$color__blue: #06b3a5;
$color__orange: #e4644b;
$color__green: #99CC33;

// styleguide only
.color__blue { background: $color__blue }
.color__orange { background: $color__orange }
.color__green { background: $color__green }
```

Would be cool to found a way to doc some variables. But for px values & other things we need to find a idea.
